[workspace]
resolver = "2"
members = [
  "packages/secretcli",
  "packages/multi-test",
  "packages/storage-plus",
  "packages/borsh-storage",
  "packages/utils",
]

[profile.release]
rpath = false
lto = true
overflow-checks = true
opt-level = 3
debug = false
debug-assertions = false
